spring.application.name=bookcut
spring.jpa.show-sql=true
spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true
spring.jpa.properties.hibernate.jdbc.time_zone=Europe/Madrid

# Correo y otros
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=bookcut2026@gmail.com
spring.mail.password=muit nzbe xigu bcby
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
spring.servlet.multipart.enabled=true

cloudinary.cloud-name=dfdze3ybn
cloudinary.api-key=918452418979669
cloudinary.api-secret=JNepK2xpjzE-5c5oBtTUOOZIBuM

# Base de datos (Usando variables de entorno para Render)
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://db.xelmttbqaessfxdiqgzm.supabase.co:5432/postgres}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:book&cut2026}
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

logging.level.org.springframework.security=TRACE
logging.level.org.springframework.web=DEBUG
