graph TD
subgraph Cliente App Móvil
A[Reserva de Cita]
end

subgraph Administrador App Web
B[Agenda Diaria E1]
end

subgraph Backend Node.js API
C[Lógica de Negocio]
end

subgraph Persistencia
D[PostgreSQL DB]
end

subgraph Infraestructura
E[Servicio Notificaciones]
end

A --> C
B --> C
C --> D
C --> E

style A fill:#D2E0F7
style B fill:#D2E0F7
style C fill:#FFE7B8
style D fill:#B9FBC0
style E fill:#F2C6C6